### ISSUE TITLE
Task 1: Introduction to Web

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/yogeshtakeo#1]
# **Installation of Node.js and Git, and Running a Console Command**

### Objective
The objective of this requirement is to install Node.js and Git on your system and run the command `console.log("Hello, world!");` to verify the installations.

### Prerequisites
1. A computer system (Windows, macOS, or Linux) with administrative privileges.
2. An internet connection to download Node.js and Git.

### Steps
1. **Download Node.js:**
   - Open a web browser and navigate to the official Node.js website: https://nodejs.org
   - On the Node.js website, locate the "Downloads" section.
   - Click on the appropriate download button based on your operating system.
   - Choose the recommended version for stability, or a specific version if required by your project.
   - Once downloaded, run the installer executable file.

2. **Install Node.js:**
   - Run the Node.js installer that you downloaded.
   - Follow the installation wizard instructions to proceed with the installation.
   - Review and accept the license agreement, if prompted.
   - Choose the installation location, or keep the default location.
   - Select additional components, if desired (e.g., npm package manager).
   - Complete the installation process by clicking the "Install" button.
   - Wait for the installation to finish.

3. **Download Git:**
   - Open a web browser and navigate to the official Git website: https://git-scm.com
   - On the Git website, locate the "Downloads" section.
   - Click on the appropriate download button based on your operating system.
   - Once downloaded, run the installer executable file.

4. **Install Git:**
   - Run the Git installer that you downloaded.
   - Follow the installation wizard instructions to proceed with the installation.
   - Review and accept the license agreement, if prompted.
   - Choose the installation location, or keep the default location.
   - Select additional components, if desired (e.g., Git Bash).
   - Choose the desired default editor for Git, or keep the default.
   - Configure line ending conversions, if desired.
   - Choose the desired terminal emulator, or keep the default.
   - Complete the installation process by clicking the "Install" button.
   - Wait for the installation to finish.

5. **Verify the Installations:**
   - Open a command prompt or terminal on your system.
   - Type `node -v` and press Enter.
   - The installed Node.js version should be displayed. Make sure the version matches the one you installed.
   - Type `git --version` and press Enter.
   - The installed Git version should be displayed. Make sure the version matches the one you installed.

6. **Run the Command:**
   - In the same command prompt or terminal, type `node` and press Enter to start the Node.js.
   - Type `console.log("Hello, world!");` and press Enter.
   - The output `Hello, world!` should be displayed in the console.
   - To exit the Node.js REPL, press Ctrl+C twice.

### Expected Output
After completing the above steps, you should have successfully installed Node.js, Git, and obtained the expected output `Hello, world!` in the console.

### Documentation
Please provide screenshots or any other relevant evidence demonstrating the successful installations of Node.js, Git, and the output of the `console.log("Hello, world!");` command.

#### Example Screenshot
![Image](https://user-images.githubusercontent.com/128008784/238532387-38b79483-f666-4a04-81f9-353cd0e9bc17.png)

**Comment by poudelg25** [comment]
Gopal Poudel
 
Grade :10

![Image](https://github.com/yogeshtakeo/yogeshtakeo/assets/105654693/5961a1cb-555e-45c8-8e69-d411cacce6e8)

**Comment by shreeshakhadka** [comment]
shreesha khadka


Grade : 10

![Image](https://github.com/yogeshtakeo/yogeshtakeo/assets/138519246/a240fafc-1437-4cbb-92c0-c0fc284ecdd2)

**Comment by GM-Frost** [comment]
Name: Nayan

Grade:10

![Image](https://github.com/yogeshtakeo/yogeshtakeo/assets/110303752/85ba2195-bb7b-4e6a-b6e1-141ea41a6bac)

**Comment by ngawangsherpa** [comment]
Ngawang Sherpa | Task 1

Grade : 10
<img width="570" alt="Screenshot 2023-07-03 at 2 10 34 PM" src="https://github.com/yogeshtakeo/yogeshtakeo/assets/78387732/9f1e67a1-6705-484f-9ff1-42aeb87007ab">

**Comment by RoneshSingh** [comment]
Annish Singh - Task 1 : Introduction to Web

Grade : 10 

![Image](https://github.com/yogeshtakeo/yogeshtakeo/assets/78497324/d78cdb83-1b50-4308-a6c8-247b46721ff3)

**Comment by YashKharel19** [comment]
YASH KHAREL

Grade: 10
Task 1: Introduction to Web


![Image](https://github.com/yogeshtakeo/yogeshtakeo/assets/7693522/ec3987c5-b000-4a25-8da3-3f9a7397787b)

**Comment by onsever** [comment]
Onurcan Sever
Task 1: Introduction to Web

Grade:10

![Image](https://github.com/yogeshtakeo/yogeshtakeo/assets/76774092/828db3da-2126-41b9-ade2-5c0101027d06)

**Comment by fakedriver** [comment]
monishon pakuwal


Grade: 10

Task 1: Introduction to Web#1

![Image](https://github.com/yogeshtakeo/yogeshtakeo/assets/58407259/8bdd3f49-1ee1-427c-825a-f082a1573e44)

**Comment by shailendrayadav7** [comment]
Name: Shailendra Yadav


Grade: 10

Task 1: Introduction to Web





![Image](https://github.com/yogeshtakeo/yogeshtakeo/assets/110005475/41e8845e-1d8b-4d54-a33a-66bd5cef1249)

**Comment by bjornbaniya** [comment]
Grade :10

![image](https://github.com/yogeshtakeo/yogeshtakeo/assets/59239240/c36e3424-b3ce-4bd0-8f78-86c6e5e20438)

**Comment by swskasingh** [comment]
swska  task 1

Grade: 10

![Image](https://github.com/yogeshtakeo/yogeshtakeo/assets/128832770/65c5aa71-e82a-4aec-b514-28f3efe3b0b2)

**Comment by smilank3** [comment]
Grade : 10

![Image](https://github.com/yogeshtakeo/yogeshtakeo/assets/36911537/e3775148-1b31-4dae-8699-be9878c9c805)

**Comment by swskasingh** [comment]
![Image 7-5-23 at 4 12 PM](https://github.com/yogeshtakeo/yogeshtakeo/assets/128832770/3f9a5c9c-9757-41ce-b3db-1f0a1a46e1f0)

**Comment by swskasingh** [comment]
[](url)
<img width="1440" alt="Screen Shot 2023-07-05 at 4 34 03 PM" src="https://github.com/yogeshtakeo/yogeshtakeo/assets/128832770/dbadee9a-1687-4464-8ead-522399f2082f">
